### ISSUE TITLE
unable to use bash variables using while loop

### ISSUE THREAD

**Issue by itnazeer** [mikefarah/yq#1047]
I am trying to pull yaml path and values using csv and use while loop to replace the paths with values like below. But, it's not working as expected.

while IFS=, read -r field1 field2
do
    yq e -i '.$field1 = $field2' input.yaml
done < input.csv

**Comment by mikefarah** [comment]
bash doesn't interpolate variables in single quotes . You can use double quotes - but this can get tricky with escaping if your expression becomes complex. Your best bet is to use the `env` operators https://mikefarah.gitbook.io/yq/operators/env-variable-operators - note that you will need to either export your variables in bash, or pass them in the command like show in the examples so that `yq` can have access to those variables.

```
while IFS=, read -r field1 field2
do
field1="$field1" field2="$field2" yq e -i '.[env(field1)] = env(field2)' input.yaml
done < input.csv
```

**Comment by itnazeer** [comment]
Hi @mikefarah 
It's throwing the error when I run the script you suggested.
Error: Value for env variable 'field2' not provided in env()

**Comment by mikefarah** [comment]
`field2` is probably blank. I'd echo it out before hand and check the bash script is doing what it's supposed to.

If you want blank values, use `strenv(field2)` instead...

**Comment by itnazeer** [comment]
You are correct.
Thanks for the swift response.
