### ISSUE TITLE
yp installed as a snap unusable as root

### ISSUE THREAD

**Issue by parmentelat** [mikefarah/yq#1190]
hiya

trying to use yq in a kubernets context, under fedora35, and running as root as this is all about setting up the cluster

because yq is not exposed as a standalone rpm from fedora - as far as I can tell - I went to snap-installing it
however I run into more trouble than what I bargained for, the simplest file operations are not working

```
 /tmp # yq --version
yq (https://github.com/mikefarah/yq/) version 4.24.2
 /tmp # cat a.yaml
a: 1
b: 2
 /tmp # yq . a.yaml
Error: open a.yaml: no such file or directory
```

bottom line is, as far as this use case is concerned, snap seems to make yq unusable, which is a pity...

what are the other options to install on f35 ?

thanks !

**Comment by mikefarah** [comment]
Yeah this is the way snap works :/ I get what they are trying to do (security) - but I think it just causes confusion.

See the snap notes here on how to work around it https://github.com/mikefarah/yq#snap-notes  - otherwise, you could always download a binary from github releases https://github.com/mikefarah/yq/releases

**Comment by parmentelat** [comment]
yeah, that's what I ended up doing, thanks for putting that together it is very helpful

and thanks for a great tool !
