### ISSUE TITLE
Won't merge mappings with null

### ISSUE THREAD

**Issue by robbieh** [mikefarah/yq#122]
Simple example:

this.yaml:
one: 1
two: 2
three: ~

that.yaml:
this:
  is: a test

After merge, three is left out.

**Comment by mikefarah** [comment]
Verified this locally

**Comment by scottrigby** [comment]
I'm looking for general purpose YAML merge functionality, so checking out this project. 

Could this issue be a feature instead of a bug? A common use case I've seen for some data merge algorithms is a new definition needing to delete a key from a previous one (in cases where the two keys would be incompatible, allowing a right YAML to specify a new key). In https://github.com/helm/helm we've adopted YAML [Null](https://yaml.org/spec/1.2/spec.html#id2803362) to signify removing a key on merge.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
