### ISSUE TITLE
Add features that evaluate YAML string in `yqlib`

### ISSUE THREAD

**Issue by leviliangtw** [mikefarah/yq#1266]
## Description

Hi, I was working on importing `yqlib` for YAML transformation features in another project, and I found out that the `yqlib` does provide the interface `StreamEvaluator` for evaluating files. However, there is no support to evaluate an input of string. Therefore, I would like to contribute a little bit to this project. 

## Expected Feature

```go
yamlStringEvaluator := NewYamlStringEvaluator()
input := " - name: \"Levi\"\n sex: \"male\""
expression := ".[].name"
output, err := yqlib.yamlStringEvaluator.Evaluate(input, expression)
if err != nil {
    log.Error(err)
}
```

## Actual Feature

```go
input := " - name: \"Levi\"\n sex: \"male\""
expression := ".[].name"

writer := new(bytes.Buffer)
reader := strings.NewReader(input)
printerWriter := yqlib.NewSinglePrinterWriter(writer)
encoder := yqlib.NewYamlEncoder(indent, colorise, printDocSeparators, unwrapScalar)
printer := yqlib.NewPrinter(encoder, printerWriter)
decoder := yqlib.NewYamlDecoder()
streamEvaluator := yqlib.NewStreamEvaluator()

yqlib.InitExpressionParser()
node, err := yqlib.ExpressionParser.ParseExpression(expression)
if err != nil {
    log.Error(err)
}

_, err = streamEvaluator.Evaluate(filename, reader, node, printer, leadingContent, decoder)
if err != nil {
    log.Error(err)
}

output := strings.TrimSuffix(writer.String(), "\n")
```

## Possible Solution

We could have a new interface `StringEvaluator`: 

```go
type StringEvaluator interface {
    Evaluate(input string, expression string) (string, err)
}
```

Then we could implement `YamlStringEvaluator`, `JSONStringEvaluator`, `XmlStringEvaluator`, and so on: 

```go
type YamlStringEvaluator struct {
    printer Printer
    decoder Decoder
    ......
}

func NewYamlStringEvaluator() StringEvaluator {
    writer := new(bytes.Buffer)
    reader := strings.NewReader()
    printerWriter := NewSinglePrinterWriter(writer)
    encoder := NewYamlEncoder(indent, colorise, printDocSeparators, unwrapScalar)
    printer := NewPrinter(encoder, printerWriter)
    decoder := NewYamlDecoder()
    return &YamlStringEvaluator{
        printer: printer
        decoder: NewYamlDecoder()
    }
    ......
}
......
```
If you are interested in this feature, I would like to discuss the details with you and create a PR for it.

**Comment by mikefarah** [comment]
Yeah - I think this would be a nice feature 👍🏼  

However, don't forget that you can mix and match decoders and encoders (that is, read an XML file and output YAML). I think the StringEvaluator interface should match the interface of the Evaluator interface - but with a string input instead of a list of files. 

I suspect with a little refactoring, a base function(s) could be written that work against the io.Reader interface and both the existing Stream/AllAtOnce implementations and the new String implementation can use. A input string could have multiple yaml documents, so this will need to be able to run the expression either in sequence against the docs (default, performant) or all at once (useful for merges and other cross-document processing).

Something like:

```go
type StringEvaluator interface {
    Evaluate(expression string, input string, printer Printer, leadingContentPreProcessing bool, decoder Decoder) (string, err)
}
```

**Comment by mikefarah** [comment]
Oop forgot to close this after is was merged in
