### ISSUE TITLE
Add winget installation option to ReadMe

### ISSUE THREAD

**Issue by russellbanks** [mikefarah/yq#1346]
yq is available from winget:

```
winget install yq
```

**Comment by mikefarah** [comment]
done - thanks for the tip!

**Comment by mloskot** [comment]
Since GitHub does not allow to comment on Releases, I've decided to hijack this thread.

I've just submitted the winget manifest with the latest v4.40.5, see
- https://github.com/microsoft/winget-pkgs/pull/130260

and I've done it using https://github.com/russellbanks/Komac/issues which turns out a great tool that make the winget manifests maintenance a breeze:

```console
komac update --id MikeFarah.yq --version 4.40.5 --urls https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_windows_386.exe,https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_windows_amd64.exe
```

then I Komac asked for GitHub token which I provided it with output from `gh auth token` and Voilà!
