### ISSUE TITLE
Duplicate keys and values outputted when using -n and evaluating an expression

### ISSUE THREAD

**Issue by kstevensonnv** [mikefarah/yq#1395]
**Describe the bug**
Duplicate keys and values outputted when using -n and evaluating an expression

Version of yq: 4.28.2
Operating system: Linux (Ubuntu 20.04.5 LTS)
Installed via: binary release

**Input Yaml**
N/A

**Command**
The command you ran:
```
yq -n '.key1 = "value1", .key2 = "value2", .key3 = "value3"'
```

**Actual behavior**

```yaml
key1: value1
key2: value2
key3: value3
key1: value1
key2: value2
key3: value3
```

**Expected behavior**
```yaml
key1: value1
key2: value2
key3: value3
```

**Additional context**
```
user@host:~$ wget https://github.com/mikefarah/yq/releases/download/v4.28.2/yq_linux_amd64
user@host:~$ chmod +x yq_linux_amd64

user@host:~$ ./yq_linux_amd64 -n '.key1 = "value1"'
key1: value1

user@host:~$ ./yq_linux_amd64 -n '.key1 = "value1", .key2 = "value2"'
key1: value1
key2: value2

user@host:~$ ./yq_linux_amd64 -n '.key1 = "value1", .key2 = "value2", .key3 = "value3"'
key1: value1
key2: value2
key3: value3
key1: value1
key2: value2
key3: value3

user@host:~$ ./yq_linux_amd64 -n '.key1 = "value1", .key2 = "value2", .key3 = "value3", .key4 = "value4", .key5 = "value5", .key6 = "value6"'
key1: value1
key2: value2
key3: value3
key4: value4
key5: value5
key6: value6
key1: value1
key2: value2
key3: value3
key4: value4
key5: value5
key6: value6
key1: value1
key2: value2
key3: value3
key4: value4
key5: value5
key6: value6
key1: value1
key2: value2
key3: value3
key4: value4
key5: value5
key6: value6
key1: value1
key2: value2
key3: value3
key4: value4
key5: value5
key6: value6
```

**Comment by mikefarah** [comment]
Hi,

The union operator (`,`) doesn't actually produce a map - it produces a set of nodes (which may themselves be a map/sequence/scalar). 

Most typical use case would be to do something like extract several different values from a document. See the [union docs](https://mikefarah.gitbook.io/yq/operators/union) for more info.

What you need is to build a map, for that you can do it explicitly via the [create map operator](https://mikefarah.gitbook.io/yq/operators/create-collect-into-object)

```bash
yq -n '{"key1": "value1", "key2":  "value2"}'
```

or implicitly create it using the [assign syntax](https://mikefarah.gitbook.io/yq/operators/assign-update)

```
yq -n '.key1 = "value1" | .key2 = "value2"'
```

Note that this looks similar to what you had, but instead of using union (which is a set of nodes), pipe the data into the next assign. This has the affect of performing the assignment on the map that was passed in...

Hope that all makes sense.

**Comment by kstevensonnv** [comment]
Thanks @mikefarah
