### ISSUE TITLE
How to get an empty string instead of `null` for non existent value?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [mikefarah/yq#1471]
```bash
declare config_name="$HOME/bash-settings.yml"
declare INFO_COLOR="$(yq ".messages.info.foreground" "$config_name")"
declare WARN_COLOR="$(yq ".messages.warn.foreground" "$config_name")"
declare ERROR_COLOR="$(yq ".messages.error.foreground" "$config_name")"
INFO_COLOR="${INFO_COLOR:-green}"
WARN_COLOR="${WARN_COLOR:-yellow}"
ERROR_COLOR="${ERROR_COLOR:-red}"
```

If `.messages.info.foreground` for instance is not defined `INFO_COLOR` must be assigned to nothing and then reassigned to `green`. How to do that in `yq`?

**Comment by mikefarah** [comment]
You can use the alternative operator: https://mikefarah.gitbook.io/yq/operators/alternative-default-value

```
yq '.messages.info.foreground // "green"' "$config_name"
```

**Comment by EmilySeville7cfg** [comment]
Thanks for the answer! 🚀

**Comment by GrayedFox** [comment]
I landed here looking for an easy way to use the alternative operator to substitute an empty string in for a null result - this is actually pretty hard to do in Bash if following the advice from shellcheck and wrapping everything in double quotes.

I ended up just using a placeholder value inside my yaml file:

```yaml
# yaml file
parent:
  possiblyUndefinedChild: "value"

# Leave this here as an empty string, it's here to make yq and bash play nice together
empty: ""
```

So that I could do:

```bash
# bash script
BASH_VAR=$(yq .parent.possiblyUndefinedChild // .empty);
```

Feels a bit bad to have to define the placeholder script value outside of the script and inside the config file but it made my bash scripting life a lot easier.

**Comment by mugen6** [comment]
why not just do it directly?

```bash
BASH_VAR=$(yq '.parent.$YQ_VAR // "" ' "$CONFIG_FILE");
```

**Comment by fracasula** [comment]
> why not just do it directly?
> 
> BASH_VAR=$(yq '.parent.$YQ_VAR // ""' "$CONFIG_FILE");

This doesn't work if the value is `false`. How to do it if the value is simply non existent?
