### ISSUE TITLE
Add an option to parse env var values as JSON strings

### ISSUE THREAD

**Issue by tukusejssirs** [mikefarah/yq#1574]
Related: #642

---

I really miss an equivalent of `--argjson` of `jq` in `yq`.

I understand that it wouldn’t be wise to make `env()` parse env var values as JSON strings by default, but it might be a good idea to add `envjson()` (or whatever name you prefer) that would process env var values as JSON strings. It should raise an error if the value is not a valid JSON string.

```bash
a='{"c": "1", "d": "a", "e": true}' yq -n '.a = env(a)'

# Current output:
a: {"c": "1", "d": "a", "e": true}

# Expected output (same as `yq -n '.a = {"c": "1", "d": "a", "e": true}'`):
a:
  c: "1"
  d: a
  e: true
```

**Comment by mikefarah** [comment]
One of `yq` features is that it tries to preserve the given formatting - which is why you are seeing it do what it is doing. If you want to format as idiomatic yaml from the JSON string, then you can either use the built in `-P/--pretty-print` flag:

```
a='{"c": "1", "d": "a", "e": true}' yq -n '.a = env(a)' -P
```

Or if you only want to style 'a' - if for example it's part of a bigger document:
```
a='{"c": "1", "d": "a", "e": true}' yq -n 'with(.a; . = env(a) | ... style = "")'
```
