### ISSUE TITLE
Infinite loop when processing a node with references

### ISSUE THREAD

**Issue by vermiculus** [mikefarah/yq#176]
YAML file:
```yaml
one: *other
two: &other hello, world
```
Shell session
```sh
yq -v r test.yml one
20:44:13 func1 [DEBU] processing 0 - requested index 0
20:44:13 func1 [DEBU] reading one in index 0
20:44:13 func1 [DEBU] <nil>
20:44:13 func1 [DEBU] processing 1 - requested index 0
20:44:13 func1 [DEBU] processing 2 - requested index 0
20:44:13 func1 [DEBU] processing 3 - requested index 0
# etc
```

`yq r test.yml one` should output `hello, world`, yeah?

**Comment by vermiculus** [comment]
Looks like the issue is in `yq.go:readProperty`.

**Comment by apeschel** [comment]
@vermiculus @mikefarah  To clarify on this, the infinite loop in yq occurs when you have an alias reference to an anchor that does not exist. In the example here, the reference is before the anchor, and so the anchor has not been parsed and does not exist in the graph by the time the reference occurs.

According to the YAML specification, an anchor *must* come before a reference to it during serialization:

> When composing a representation graph from serialized events, an alias node refers to the most recent node in the serialization having the specified anchor.

The following will work:

```
two: &other hello, world
one: *other
```

This will result in an infinite loop.

```
foo: *bar # There is no bar anchor.
```

So to reiterate, the infinite loop problem occurs when there is an alias reference to an anchor that does not exist in the graph. Doing this should ideally result in yq throwing an error referring to that bad anchor, rather than going into an infinite loop.

**Comment by apeschel** [comment]
Here are some relevant examples:


## Referencing a non-existing anchor causes an infinite loop:

### Example 1:

**Input:**

```
foo: *foo # foo anchor does not exist, yq will enter an infinite loop
```

**Expected output:**

Exit with failure, and render an error message referring to the invalid alias.

**Actual output:**

yq enters an infinite loop

### Example 2:

In this example, the foo anchor is not serialized before this alias, which is invalid YAML. yq enters an infinite loop.

**Input:**

```
bar: *foo
foo: &foo "foo"
```

**Expected output:**

Exit with failure, and render an error message referring to the invalid alias.

**Actual output:**

yq enters an infinite loop

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
