### ISSUE TITLE
join(",") not working as expected

### ISSUE THREAD

**Issue by salpark** [mikefarah/yq#1931]
**Describe the bug**

`join(",")` is not working as expected.

---

If have an array of values:
```bash
$ yq --null-input '["/pets","/pets/{petId}"]'
- /pets
- /pets/{petId}
```

I can join them together and this works as expected:
```bash
$ yq --null-input '["/pets","/pets/{petId}"] | join(",")'
/pets,/pets/{petId}
```

If I generate exactly the same array as above but via a more complex query:
```bash
$ curl -s https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml |\
yq '.paths.[] |pick(["get","post"]) | [path | .[1]]'
- /pets
- /pets/{petId}
```

And if I pipe it through join it does not combine the array as expected:
```bash
$ curl -s https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml |\
yq '.paths.[] |pick(["get","post"]) | [path | .[1]] | join(",")'
/pets
/pets/{petId}
```

Expected output:
```csv
/pets,/pets/{petId}
```

Version of yq: 
`v4.40.5`
Operating system: 
`Darwin MC435-D98A-15FF.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 arm64 arm Darwin`
Installed via: 
`homebrew`

**Comment by mikefarah** [comment]
Hey, thanks for raising.

The issue here is that this expression: `'.paths.[] |pick(["get","post"]) | [path | .[1]]'` actually produces _two_ arrays with a single element each. It's hard to see that due to the nature of how `yaml` prints out arrays, but if you output as JSON, you'll see:

```
./yq '.paths.[] |pick(["get","post"]) | [path | .[1]]' -oj test.yaml
[
  "/pets"
]
[
  "/pets/{petId}"
]
```

This is caused by the splat`.[]` you have at the start. You'll need square brackets that encapsulates that expression to put everything back into a single array again:

```
./yq '[.paths.[] |pick(["get","post"]) | path | .[1]]' -oj test.yaml 
[
  "/pets",
  "/pets/{petId}"
]
```

And now the join will work on that array:
```
./yq '[.paths.[] |pick(["get","post"]) | path | .[1]] | join(",")' -oj test.yaml
"/pets,/pets/{petId}"
```

**Comment by salpark** [comment]
@mikefarah brilliant, thanks for the response 👍
