### ISSUE TITLE
generated array seems not working (e.g. with sort, unique)

### ISSUE THREAD

**Issue by williamjoy** [mikefarah/yq#2056]
**Describe the bug**
`sort` or `unique` has no effect on generated array in some case

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.44.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
x:
  a: 1
y:
  a: 2
z:
  c: 3
```

**Command**
The command you ran:
```
yq '.[]|keys| map(sub("a","c")) | unique' test.yaml
```

**Actual behavior**

```yaml
- c
- c
- c
```

**Expected behavior**

```yaml
-c
```

**Additional context**
```
yq '(.[]|keys| map(sub("a","c"))) | unique' test.yaml |yq unique
- c
```

**Comment by mikefarah** [comment]
This is because you're actually working with 3 arrays, each of which has a single element. Unique then runs against each of the arrays and returns `c` for each of them 😅 

The splat operator `.[]` splits your map into a set of 3 separate value nodes, then `keys` runs against each set, returning 3 arrays with a single entry each.

There are a few different ways to get what you want, you could do it like this:

```
/yq '[.[][] | key] | map(sub("a","c")) | unique' examples/data1.yaml
```

Explanation:
- `.[]` splats the values of the parent map, and `.[] | .[]` or just `.[][]` will splat down to the children map values.
- `key` returns the single key for each child
- Wrapping that whole thing in square brackets puts those keys into a single array
