### ISSUE TITLE
Failed to convert JSON to YAML if we don't pass --prettyPrint (3.1.1)

### ISSUE THREAD

**Issue by rjcoelho** [mikefarah/yq#357]
We shouldn't need to pass --prettyPrint in order to convert JSON to YAML. In other words, please make it the default.

This is a breaking change (prior to 3).

**Comment by mikefarah** [comment]
The thing is JSON is a subset of YAML. yq has no idea that you're giving it JSON file and want to format it as idiomatic YAML. This clashes with the requirement of keeping YAML formatting when making changes.

The only way I see to resolve that is having a prettyPrint flag, having it default would make YQ always change the formatting of all YAML documents.

**Comment by rjcoelho** [comment]
My use case for YQ is to convert to/from json/yaml. It doesn't make sense to need to pass "prettyPrint" flag to do so, since "prettyPrint" is syntax indentation, in my interpretation. 

Why did this change from pre 3.x ? Would it help to add an explicit flag to tell what is the input/output format ?

**Comment by mikefarah** [comment]
So a new feature of V3 is that it (tries) to keep the yaml formatting and comments as much as possible (which V2 didn't do).

JSON is a subset of YAML, so a JSON formatted string can be read by a YAML parser as YAML. yq doesn't actually know it's reading JSON. It reads the document as YAML. 

Since yq now keeps original document formatting, by default it will keep the 'json' formatting style of the yaml document and print that.

The prettyPrint flag tells makes is set the formatting to idiomatic yaml. 

Not sure how I can make this clearer sorry.
