### ISSUE TITLE
Array items insertion in .yaml file

### ISSUE THREAD

**Issue by avinashGuptaIos** [mikefarah/yq#405]
i am facing issues while storing all the array elements into .yaml  file
i m not getting that how can we insert all elements of array , at once in .yaml file.
instead of doing
yq w sample.yaml b.d[+] "new thing" 
yq w sample.yaml b.d[+] "new thing"
yq w sample.yaml b.d[+] "new thing"

again and again,
i want to pass the array name like ${elementsArray} , so that it can insert all the records at once in .yaml file.
like:
yq w sample.yaml b.d[+] ${elementsArray}

can u please help me out for this.

**Comment by mikefarah** [comment]
Not quite sure what you are trying to do - looks like you could use a script file? https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update

Otherwise, if you could follow the formatting of a feature request and should the input yaml, desired command and output yaml it would be a little clearer.

**Comment by avinashGuptaIos** [comment]
thanks
