### ISSUE TITLE
JSON to Yaml conversion error on yes boolean

### ISSUE THREAD

**Issue by autarchprinceps** [mikefarah/yq#467]
**Describe the bug**
I noticed this problem, when converting to json and then back to yaml. We have a field which has the STRING value of yes, but when converting a "yes" from Json, yq puts a yes instead of a "yes" which is not the string yes, but the boolean true. 
```
❯ cat test.yaml
test: "yes"
❯ yq r test.yaml -j
{"test":"yes"}
❯ yq r test.yaml -j | yq r - --prettyPrint
test: yes
```

Reversely a boolean true in yaml is converted to string yes in json as well, which while secondary to my use case seems like an even more grave issue.
```
❯ cat test.yaml
test: yes
❯ yq r test.yaml -j
{"test":"yes"}
```

When operating with true as either boolean or string, yq reacts correctly however. I assume this means, that to fix this whatever exemption of typical string behaviour is applied to true and false is missing from yes and no.

version of yq: 3.3.2
operating system: macOS

**Comment by mikefarah** [comment]
yq's underlying yaml parser (go-yaml) supports version 1.2 spec of yaml, which no longer has 'yes' as a boolean value (https://yaml.org/spec/1.2/spec.html) - that's why the value is unquoted.

1.1 parsers will interpret that as the boolean true, whereas 1.2 will interpret it as the string 'yes'. Fantastic I know.

As a work around, you can force quotes using the style tag https://mikefarah.gitbook.io/yq/usage/value-parsing#the-style-flag

**Comment by autarchprinceps** [comment]
Thanks for the super quick answer. @mikefarah 
Fantastic indeed. Didn't know that one.

The style flag applies to yq n, I don't think I can use it on json to yaml conversion, as far as I can see.
