### ISSUE TITLE
xq is missing for mac installation

### ISSUE THREAD

**Issue by y0y0z** [mikefarah/yq#491]
firstly, thank you for the work.

i've installed yq from brew

```shell
$ brew info yq
yq: stable 3.3.2 (bottled)
Process YAML documents from the CLI
https://github.com/mikefarah/yq
Conflicts with:
  python-yq (because both install `yq` executables)
/usr/local/Cellar/yq/3.3.2 (5 files, 6MB) *
  Poured from bottle on 2020-07-16 at 10:26:40
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yq.rb
License: MIT
==> Dependencies
Build: go ✔
```

when readying `yq` documentation, i saw the [support for xml](https://github.com/kislyuk/yq#xml-support)

> `yq` also supports XML. The `yq` package installs an executable, `xq`

but `xq` does not exist on the system after installing `yq` brew formulae

**Comment by mikefarah** [comment]
that's the other yq ;)

**Comment by sarimarton** [comment]
> that's the other yq ;)

Can you expand on that, @mikefarah ? I'm bumping into the same problem.

**Comment by mikefarah** [comment]
This one here: `https://github.com/kislyuk/yq` - though I am curious, what's the use case for it?

I had a look at encoding yaml to xml, however the process would end up making up its own schema, particularly around arrays and attributes. 

What are you trying to do?

**Comment by sarimarton** [comment]
I'm trying to convert xml to json or yaml to get my emails. Something like this:

curl -u username@gmail.com:xxxxxxxx --silent https://mail.google.com/mail/feed/atom | yq -o=j eval -

But it returns with the whole xml wrapped in a string.

**Comment by anilkumarvemulapalli** [comment]
I've also been confused by this.

@mikefarah, at least for me the main use case is to use all the yq goodness but on XML files, by performing an "xml to json" (or "xml to yaml", whatever is easier) before using the real yq on a json/yaml input.
So the conversion is xml->yaml/json, not the other way round.

Looking at "the other yq", the schema of the resulting json after doing xml->json may be a bit "special" (e.g. xml attributes on fields will be rendered as "@attribute_name":"attribute_value") but if this means you can process an XML with yq then is worth the effort (alternatives such as using sed/awk/etc to parse an xml are not an option for me).

So, all in all, although the title of this issue is a bit different, I think the request/idea would be to support xml input (either by having an extra command line flag or by auto-detecting the input not being yaml/json and being valid xml) and convert between xml to whichever "native" format yq supports better (yaml or json). From then on, yq is just processing a "normal/native" yaml/json input.

**Comment by horacimacias** [comment]
I've also been confused by this.

@mikefarah, at least for me the main use case is to use all the yq goodness but on XML files, by performing an "xml to json" (or "xml to yaml", whatever is easier) before using the real yq on a json/yaml input.
So the conversion is xml->yaml/json, not the other way round.

Looking at "the other yq", the schema of the resulting json after doing xml->json may be a bit "special" (e.g. xml attributes on fields will be rendered as "@attribute_name":"attribute_value") but if this means you can process an XML with yq then is worth the effort (alternatives such as using sed/awk/etc to parse an xml are not an option for me).

So, all in all, although the title of this issue is a bit different, I think the request/idea would be to support xml input (either by having an extra command line flag or by auto-detecting the input not being yaml/json and being valid xml) and convert between xml to whichever "native" format yq supports better (yaml or json). From then on, yq is just processing a "normal/native" yaml/json input.

would you be open to something like this? 
something like https://github.com/basgys/goxml2json combined with yq could extend its support for XML.
I'd be happy to help if you think this fits.

**Comment by mikefarah** [comment]
Thanks for the tip @horacimacias - I've implemented XML support in the latest release (4.17.2) let me know what you think!

**Comment by sarimarton** [comment]
@mikefarah Thank you, thank you, thank you, it works beautifully! I put my home automation project aside because of that roadblock that time, and now I'm picking up.

**Comment by horacimacias** [comment]
nicely done, thanks @mikefarah ! 👏 

Just to give an example, in my case using yq means using 

```bash
yq e -p=xml '.ProductSection.Property[] | select(.+key == "envname") | .+value' test.xml
```

instead of

```bash
cat test.xml | xmllint --xpath "string(//*[local-name()='ProductSection']/*[local-name()='Property'][@*[local-name()='key' and .='envname']]/@*[local-name()='value'])" -
```

when trying to get the `value` attribute of the `Property` where `key=envname` from an xml like this:
```xml
   <ProductSection required="false">
    <Info>system information</Info>
      <Property key="ip0" type="string" qualifiers="MinLen(0),MaxLen(255)" value="" required="false" userConfigurable="true">
        <Label>IPv4 Address</Label>
        <Description>Enter IPv4 address</Description>
      </Property>
      <Property key="netmask0" type="string" qualifiers="MinLen(0),MaxLen(255)" value="255.255.255.0" required="false" userConfigurable="true">
        <Label>IPv4 Netmask</Label>
        <Description>Enter IPv4 Netmask</Description>
      </Property>
      <Property key="gateway" type="string" qualifiers="MinLen(0),MaxLen(255)" value="" required="false" userConfigurable="true">
        <Label>IPv4 Gateway</Label>
        <Description>Enter IPv4 Gateway</Description>
      </Property>
      <Property key="dns" type="string" qualifiers="MinLen(0),MaxLen(255)" value="" required="false" userConfigurable="true">
        <Label>DNS Server</Label>
        <Description>Enter DNS server IP addresses.</Description>
      </Property>
      <Property key="hostname" type="string" qualifiers="MinLen(0),MaxLen(255)" value="" required="true" userConfigurable="true">
        <Label>Hostname</Label>
        <Description>Enter Hostname.</Description>
      </Property>
      <Property key="envname" type="string" qualifiers="MinLen(0),MaxLen(255)" value="test" required="true" userConfigurable="true">
        <Label>Environment Name</Label>
        <Description>Enter Environment Name</Description>
      </Property>
   </ProductSection>
```
