### ISSUE TITLE
support conversion of jsonl content to multi-document yaml content

### ISSUE THREAD

**Issue by tkellen** [mikefarah/yq#494]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to convert jsonl (one json document per line) content to yaml with `---` separators between each document. This is already possible for yaml -> json (`yq r -j -d'*'`).

**Describe the solution you'd like**
It would be great if `echo '{"test":"thing"}\n{"other":"thing"}' | yq r -P -` produced:
```yaml
test: thing
---
other: thing
```

It currently produces:
```yaml
test: thing
```

**Describe alternatives you've considered**
I am currently using xargs and converting each line individually. For large collections this is pretty slow.

**Additional context**
Interestingly, `echo '{"test":"thing"}\n{"other":"thing"}' | yq r -d'*' -P -` produces:
`Error: yaml: line 1: did not find expected <document start>`

...while the invalid jsonl `echo '{"test":"thing"}\n---\n{"other":"thing"}' | yq r -d'*' -P -` produces a single yaml document:
```yaml
test: thing
other: thing
```

**Comment by tkellen** [comment]
Also, assuming this is a feature you'd support I would be happy to implement it if you tell me what command you'd like the command line invocation should be. Also, thanks for making this tool!

**Comment by mikefarah** [comment]
Oops just noticed this comment - sorry I try to keep on top of all issues but sometimes get lost.

This actually works:

```
echo '{"test":"thing"}\n---\n{"other":"thing"}' | yq r - -d'*'
```

Note that when you run the `read` command with the -d'*' it won't print document separators (long story short, this is because read is intended to read and collect bits out of yaml, rather than represent the document as a whole).

If you were pipe that in to the write command (which is intented to update a yaml and so prints it out entirely) you'd get what you want, though it's a bit hackish because you need to give a fake update command.

```
echo '{"test":"thing"}\n---\n{"other":"thing"}' | ./yq w - -P --style=single '*'
```

It's very generous of you to offer your time! Not sure if that offer is still there 2 months later! (My fault I'm sorry).

I think it'd be neat to add a 'format' command to `yq` so you could then do:

```
echo '{"test":"thing"}\n---\n{"other":"thing"}' | ./yq format -P -
```

Format could also take the `--style` and `-j` flags to control styling / format as json.

Thoughts?

**Comment by mikefarah** [comment]
v4 (in alpha) supports this
