### ISSUE TITLE
Support for path expressions in writing new value

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#602]
Big fan of the tool, but I really wish the tool supports writing a value from a path instead of just literal values.

If we have `foo.yml` like:

```yaml
a:
  desc:
  value: 1
b:
  desc:
  value: 2
```

And we run a command:

```bash
yq w foo.yaml '*' '*.value'
```

it could output

```yaml
a: 1
b: 2
```

The Python version overpowers on this regard, because of the powerful support built in for `jq`. Just by doing `yq -y '.[] |= .value' yaml`

**Comment by mikefarah** [comment]
check out the v4 beta build, it uses jq syntax and you can do exactly that

```
yq e '.[] |= .value' test.yml
```

**Comment by inianv** [comment]
Thanks @mikefarah, good news for me! I've decent jq-fu at hand. A big kudos for v4 and hoping to see much more new features added.

**Comment by mikefarah** [comment]
Thanks @inianv appreciate that 👍 

I'd love an additional hand if you have the time - I don't have anything specific in mind atm - but if you see something that you'd use often in jq but missing in yq I'd be more than happy to take a PR. Otherwise I've only added support for objects and arrays in multiply and add - if you were to add implementations (as per jq) for strings and/or numbers that'd be ace too.

**Comment by inianv** [comment]
> check out the v4 beta build, it uses jq syntax and you can do exactly that
> 
> ```
> yq e '.[] |= .value' test.yml
> ```

So the idea is, starting v4 the DSL for `yq` is going to completely align with `jq`'s or only a handful of features @mikefarah

**Comment by mikefarah** [comment]
Complete would be cool - though I suspect `jq` has many features that are seldom used. I'm aiming for the ones most often used atm
