### ISSUE TITLE
How can I install latest v3 via snap?

### ISSUE THREAD

**Issue by bitsofinfo** [mikefarah/yq#625]
How can I install the latest v3 via snap? I am not ready to move to v4 as its breaking my CI

this only list 4.2.0.... https://snapcraft.io/yq

**Comment by mikefarah** [comment]
It looks like snapcraft has a concept of 'tracks' which will allow me to publish major `yq` versions onto different tracks. I have to manually raise a request to be able to do this https://forum.snapcraft.io/t/enable-tracks-for-yq/21892

Until then - you could simply use wget to get the v3 release to avoid breaking your build.

**Comment by StianOvrevage** [comment]
I have a related problem. Since snap got updated from v3 to v4 suddenly GitHub Actions builds started breaking during x-mas.

So, I update to v4 but the problem now is that the Ubuntu PPAs have not been updated for almost 6 months, and does not have v4 yet, so I cannot install it on my local machine. I cannot use snap to install v4 since I'm on WSL.

I'll work around by manually installing one of the versions in one of the systems, but it would be good to easily install the same version (either v3 or v4) with both methods (snap and PPAs).

**Comment by mikefarah** [comment]
Tracks have been enabled!

```
snap install yq --channel=v3/stable
```
