### ISSUE TITLE
Add support for built-in function 'unique, unique_by(path_exp)'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#78]
Add support for built-in [function 'unique, unique_by(path_exp)'](https://stedolan.github.io/jq/manual/#example47)

```
The unique function takes as input an array and produces an array of the same elements, in sorted order, with duplicates removed.

The unique_by(path_exp) function will keep only one element for each value obtained by applying the argument. Think of it as making an array by taking one element out of every group produced by group.
```

**Comment by funkeyfreak** [comment]
Greetings @mikefarah - was this ever added to yq? I'd be happy to lend a hand :)

**Comment by mikefarah** [comment]
Nope, that'd be Ace!
________________________________

**Comment by lexuzieel** [comment]
I'm too interested in this feature as it seems currently there is no way to do this (correct me if I'm wrong) without outputting the YAML file into JSON, process it with jq and then pass it back into yq. Did you have a chance to tackle this? @funkeyfreak 

Also, maybe it's worth adding a merge flag for this operation, since it's common for arrays. Something like this:
```bash
$ yq -P e '.a *+u .b' <(echo '{a: ["banana", "apple", "orange"], b: ["banana", "orange"]}')
- banana
- apple
- orange
```
