### ISSUE TITLE
'unique' does not seem to work?

### ISSUE THREAD

**Issue by dlampa** [mikefarah/yq#827]
**Describe the bug**
'unique' operator appears not to be working.

Version of yq: 4.8.0
Operating system: linux
Installed via: binary release

**Input Yaml**
data1.yml:
```yaml
- a
- b
- a
- b
```
**Command**
The command you ran:
```
yq eval 'unique' data1.yml
```

**Actual behavior**
```
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:2.
        unmatched text: "u"
```

**Expected behavior**

```yaml
- a
- b
```

**Comment by mikefarah** [comment]
Unique was added in 4.9.0 :)
________________________________
From: Damir Lampa ***@***.***>
Sent: Friday, May 21, 2021 3:34:27 PM
To: mikefarah/yq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mikefarah/yq] 'unique' does not seem to work? (#827)


Describe the bug
'unique' operator appears not to be working.

Version of yq: 4.8.0
Operating system: linux
Installed via: binary release

Input Yaml
data1.yml:

- a
- b
- a
- b

Command
The command you ran:

yq eval 'unique' data1.yml


Actual behavior

Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:2.
        unmatched text: "u"


Expected behavior

- a
- b

**Comment by dlampa** [comment]
:man_facepalming: That's great , hard to keep up lately :smile:  Thanks!
