### ISSUE TITLE
Undocumented text matching syntax for `select`

### ISSUE THREAD

**Issue by phreed** [mikefarah/yq#839]
## Description of the Issue

Matching of strings is ill defined.

Version of yq: 4.9.3
Operating system: windows/ubuntu
Installed via:

    windows: choco install yq
    ubuntu: via wget

https://github.com/mikefarah/yq/blob/master/pkg/yqlib/doc/Select.md#select-elements-from-array

### Actual
It is unclear what type of matching is being used in `select`.
They look like some variant of `globbing`. 
```
.[] | select(. == "*at")
```
Which matches things like `cat` and `goat` but not `dog`.
This is fine as far as it goes but the simple example is insufficient.
As near as I can tell the logic is in [matchKeyString.go](https://github.com/mikefarah/yq/blob/master/pkg/yqlib/matchKeyString.go)

### Expected
Documentation or a reference to a document which explains how the mapping is performed.
Is the pattern required to start with '*'?

## Additional Information: Feature?

Maybe using a [globbing library](https://github.com/ryanuber/go-glob).

I would like [regular expressions](https://golang.org/pkg/regexp/) with a syntax something like.
```
.[] | select(. ~= ".*at")
```

**Comment by mikefarah** [comment]
Regex is actually already built in - https://mikefarah.gitbook.io/yq/operators/string-operators#test-using-regex

I just need to update the select docs, been a while since I've looked at them. 

fwiw - the wildcard syntax is kind of a hangover from yq 3 - where I didn't have advanced syntax - but it should be documented better 👍🏼

**Comment by mikefarah** [comment]
Updated select docs
