### ISSUE TITLE
safelyRenameFile [ERRO] when updating yaml file using the docker command

### ISSUE THREAD

**Issue by lewisgauss** [mikefarah/yq#884]
**Describe the bug**
I have an Azure pipeline that renames the nginx-ingress yaml file using the docker command like this
After updating to 4.9.7, it no longer renames properly. I now get a safelyRenameFile error, with permission denied. 

Version of yq: 4.9.7
Operating system: Linux
Installed via: Docker command

**Input Yaml**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
```

**Command**

```
docker run --rm -v /home/vsts/work/1/s/packages/ui-library:/workdir mikefarah/yq e .metadata.name="pr-4887-ingress" -i manifests/nginx-ingress.yml
```

**Actual behavior**

Bash error
```
16:17:52 safelyRenameFile [ERRO] Failed copying from /tmp/temp788489175 to manifests/nginx-ingress.yml
16:17:52 safelyRenameFile [ERRO] open manifests/nginx-ingress.yml: permission denied
```

**Expected behavior**

metadata.name is updated without error

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pr-4887-ingress
```

**Comment by LuayGrira** [comment]
I think I commented in the wrong issue, but I have the same problem.
https://github.com/mikefarah/yq/issues/883#issuecomment-875727691

**Comment by mikefarah** [comment]
I think you're right @LuayGrira, it looks like this was introduced in order to fix a security issue (CWE-22) @bison-monica.

On reading CWE-22 I don't think it applies to `yq`, it's more for something like a public http app where the user could give a path outside the public website directory and gain access to secure files. (https://cwe.mitre.org/data/definitions/22.html)

That change has been reverted in 4.9.8
