### ISSUE TITLE
Fail to go get 3.4.1

### ISSUE THREAD

**Issue by hw676018683** [mikefarah/yq#994]
go get github.com/mikefarah/yq@3.4.1

Output:
```
go get github.com/mikefarah/yq@3.4.1: github.com/mikefarah/yq@v1.15.1-0.20201018214059-6afc2e918934: invalid version: go.mod has post-v1 module path "github.com/mikefarah/yq/v3" at revision 6afc2e918934
```

GO VERSION: `go version go1.17.1 darwin/amd64`

**Comment by mikefarah** [comment]
Not sure why that's happening, however I am no longer maintaining v3 of yq - I highly recommend updating to v4 as v3 hasn't been touched since I released it (which means it hasn't had any dependency updates nor rebuilds with a newer go compiler to fix potential security vulnerabilities. Check out the guide here https://mikefarah.gitbook.io/yq/upgrading-from-v3 - it should be pretty straight forward to update.
